### ISSUE TITLE
Chrono Trigger has small graphical glitches when a battle starts

### ISSUE THREAD

**Issue by the-importer** [MiSTer-devel/SNES_MiSTer#38] opened 2019-02-24 22:17 UTC
It happens on my 4KTV and my LCD monitor. I tried different resolutions and Vsync options, but I still get the issue.

**Comment by James-F2** [comment] 2019-02-25 13:40
Only happens on HDMI, not VGA.
It is probably scaler related.

Save attached.
Go t into town and fight the creatures.
[Chrono Trigger (U) [!].zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/2900744/Chrono.Trigger.U.zip)

**Comment by the-importer** [comment] 2019-02-25 13:52
> Only happens on HDMI, not VGA.
> It is probably scaler related.
> 
> Save attached.
> Go up into Truce Canyon (mountain) and fight the creatures.
> [Chrono Trigger (U) [!].zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/2900744/Chrono.Trigger.U.zip)

Actually, my 2nd screen, that old LCD monitor that I was mentioning, is hooked via VGA and the issue is actually worst on it. Also, why would I fight the creature in your save game? Will is fix anything?

**Comment by James-F2** [comment] 2019-02-25 13:57
I only see this with HDMI.
Do you use the VGA output from the IO board?

The save file I posted because it takes 10 minutes till you actually fight monsters in this game, and you did not provide one.
It is for developers who want to test this bug quickly.

**Comment by the-importer** [comment] 2019-02-25 14:30
> I only see this with HDMI.
> Do you use the VGA output from the IO board?
> 
> The save file I posted because it takes 10 minutes till you actually fight monsters in this game, and you did not provide one.
> It is for developers who want to test this bug quickly.

Yes, I use VGA from the IO board. As for the your save data, I don't really need it. Right at the beginning, I can just go to the forest, fight the monsters there and see the glitch.

**Comment by James-F2** [comment] 2019-02-25 14:34
Again, the save is not for you but for developers who do not know where the forest is or played chrono trigger, and want to test the reported bug quickly.

Also, sometime this bug appears only after reset.

**Comment by James-F2** [comment] 2019-02-25 17:46
Do you have vga_scaler enabled in mister.ini?

**Comment by the-importer** [comment] 2019-02-25 19:54
> Do you have vga_scaler enabled in mister.ini?

I fiddled with it, didn't change anything. If I didn't know any better, it's almost like CT changes resolution when entering battle mode (similar to how how Chrono Cross switches from 240p to 480i in the menu).

**Comment by James-F2** [comment] 2019-03-04 20:07
I can see the "before fight" image flicker when loading a rom.
It's probably HDMI buffer related.

**Comment by the-importer** [comment] 2019-03-04 20:12
@sorgelig
And I see the issue with both VGA (on an old LCD monitor) and HDMI on my TV.

**Comment by James-F2** [comment] 2019-03-04 20:13
@the-importer 
Can you please post your mister.ini file, that would help solve the problem.

**Comment by paulb-nl** [comment] 2019-03-14 14:08
I don't see this issue with VGA to CRT or OSSC. 

The game does a lot of HDMA writes per frame to register 2130-2133. Interlaced is one of the things set with 2133. So I made a build with interlaced disabled in the Ascal scaler and the issue was gone.

Appearantly interlace is not enabled long enough for the analog output to be affected but the scaler reacts immediately.

Either the game enables interlace by accident or it is a bug in the SNES core.

**Comment by James-F2** [comment] 2019-05-07 06:40
If it is the game that write to 2133 then this issue can be closed.
@paulb-nl  can you confirm that it is indeed the game that does this?

**Comment by sorgelig** [comment] 2019-05-07 07:40
probably interlace mode can be locked at some point of screen to eliminate sporadic changes while screen drawing

**Comment by paulb-nl** [comment] 2019-05-07 09:30
@James-F2  I have checked with Mesen-S and the game enables interlace on scanline 8 and disables on scanline 9 for 2 frames in a row.

**Comment by James-F2** [comment] 2019-05-07 09:37
Thank you.
So it is obviously not a bug in the core or scaler.
Should it be fixed as a workaround quirk or ignored?

**Comment by paulb-nl** [comment] 2019-05-07 10:05
Well It's kind of a bug in the scaler because I don't think it should detect interlace when interlace is only enabled for 1 scanline of the frame.

Could probably be fixed if the scaler only detects interlace in Vblank or skip detection and send interlace enabled bit to the scaler.

**Comment by sorgelig** [comment] 2019-05-07 11:26
It's not only about scaler. SNES glue logic i wrote disables scandoubler if interlace is detected (scandoubler is not compatible with interlace). So it doesn't lock interlace mode either. So i need to update my code to not react on sporadic changes of interlace mode.

**Comment by paulb-nl** [comment] 2019-05-14 10:06
Latching the INTERLACE flag only on Vsync start seems to be working for both.
````verilog
if(~old_vsync & VSync) begin
	frame_hres <= tmp_hres | ~scandoubler;
	tmp_hres <= HIGH_RES;
	Interlace_l <= INTERLACE;
end
````

**Comment by sorgelig** [comment] 2019-05-14 17:25
i forgot about this issue :)
will add it.

**Comment by James-F2** [comment] 2019-05-15 15:29
Seems to be fixed in 20190515.
Thank you paulb-nl & sorgelig!

**Closed** 2019-05-15 15:53 UTC
