### ISSUE TITLE
WILD GUNS: Unplayable after starting game, heavy flickering and slowdown

### ISSUE THREAD

**Issue by cpmattes** [MiSTer-devel/SNES_MiSTer#207] opened 2020-02-09 09:59 UTC
Like mentioned in title, after starting US or JAP Version of Wild Guns with SNES_20200108.rbf everything seems to be fine, title screen and menu are flawless, controller is reacting. After choosing a character and starting the game, the picture is flickering heavily and gameplay is evenly slowed down. Using 128MB ram expansion, setup cooled passive and with a noctua.

**Comment by paulb-nl** [comment] 2020-02-09 10:25
This has already been fixed.

@sorgelig please make a new release

**Comment by sorgelig** [comment] 2020-02-10 16:55
i didn't release yet because i see debates when one commit fixes one thing but breaks others. So i'm unsure if it's ready to release or not.

**Comment by paulb-nl** [comment] 2020-02-10 17:14
It is ready for release. The regressions have been fixed.

**Comment by sorgelig** [comment] 2020-02-11 00:23
alright. will release tomorrow

**Comment by Left-Empty** [comment] 2020-03-12 04:18
Hello,
I have just tried it, and the issue seems to still be here.

**Comment by paulb-nl** [comment] 2020-03-12 12:48
Works fine here:
https://youtu.be/UZvSomwdStI

**Comment by cpmattes** [comment] 2020-03-12 12:50
Last update fixed it for me!

**Comment by Left-Empty** [comment] 2020-03-12 16:39
It seems my wonderful little MiSTer wants me to look bad here: for two days the game exhibited the glitch. 
I try again today after watching paulb-nl's video, using the US version: it works. I tried again my Japanese version. It works.
I apologize.

**Comment by SegaSnatcher** [comment] 2020-04-13 23:44
> Last update fixed it for me!

Probably best to close this issue now.  Thanks

**Closed** 2020-04-14 15:12 UTC
