### ISSUE TITLE
Seth Bling - Super Mario World Jail Break 

### ISSUE THREAD

**Issue by amoore2600** [MiSTer-devel/SNES_MiSTer#87] opened 2019-05-31 03:40 UTC
I have a cart with the [Seth Bling - Super Mario World Jail Break](https://www.youtube.com/watch?v=Ixu8tn__91E) 

This cart and the save ram can be ripped to via a UFO Pro 8 or Analogue NT

From the rip of the cart and save ram, the Jail break can be played on:

- Real SNES hardware with a UFO Pro 8  
- Real SNES with an Everdrive 
- Real SNES with original cart
- Analogue NT with original cart

However the jail break fails to run on MiSTer.  

I have attached the save ram file.  Matching rom has a check sum crc32 b19ed489

[SUPER MARIOWORLD - JB.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/3239630/SUPER.MARIOWORLD.-.JB.zip)

**Comment by sorgelig** [comment] 2019-05-31 16:05
It's unclear what exactly not working. ROM itself or save?
Note: saves never meant to be transferable. It may or may not be transferred from other platform. It's not a bug.

**Comment by amoore2600** [comment] 2019-05-31 16:07
It's the save that does not work. It nolonger does the jailbreak.

**Comment by sorgelig** [comment] 2019-05-31 16:08
MiSTer doesn't need jailbreaks. It accepts any modified ROM.
There are many SMW mods you can play directly.

**Comment by paulb-nl** [comment] 2019-06-08 19:51
This appears to be an issue with SRAM mirroring.

It works in Bsnes and it mirrors SRAM of Super Mario World to 70-7D:0000-FFFF and F0-FF:0000-FFFF.

Removing "and CA(15) = '0'" from here makes it work: https://github.com/MiSTer-devel/SNES_MiSTer/blob/71bc10007fc690896cf886f10d7b05ce4595b859/src/chip/DSP/DSP_LHRomMap.vhd#L109

**Comment by sorgelig** [comment] 2019-06-09 16:56
should be fixed in today's release

**Comment by amoore2600** [comment] 2019-06-09 18:17
Freaking Awesome!

**Comment by James-F2** [comment] 2019-06-10 07:04
@amoore2600 
Please use the "Close Issue" button.

**Closed** 2019-06-10 10:43 UTC
