### ISSUE TITLE
Star Ocean (96MBit uncompressed) will not boot

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#43] opened 2019-02-27 08:01 UTC
The uncompressed game will boot to black screen.
It is 12.5MByte, and maybe exceeds the MiSTer rom capacity.

The regular SDD-1 (compressed) version works fine.

**Comment by sorgelig** [comment] 2019-02-27 09:52
This is not a bug. It's just hack using some specific mapper.
Marked as enhancement with low priority and the main priority is to fix the bugs in original games.

**Comment by James-F2** [comment] 2019-03-04 19:24
It boots now, thank you!

**Closed** 2019-03-04 19:24 UTC
Labels: enhancement
