### ISSUE TITLE
Ken Griffey Jr. Presents Major League Baseball

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/SNES_MiSTer#20] opened 2019-01-02 03:14 UTC
When selecting the option "Season" for the game mode it doesn't work. You will see a weird graphical glitch and the game either freezes up or resets.

**Comment by James-F2** [comment] 2019-01-26 13:51
Confirmed.

**Comment by James-F2** [comment] 2019-01-30 11:23
Fixed

**Comment by James-F2** [comment] 2019-03-04 19:31
Looks like it was fixed.
Some commit from March 3rd or 4th fixed this bug.
Needs confirmation by another person and close.

**Comment by James-F2** [comment] 2019-03-05 04:05
Confirmed to be fixed by others.

Main MiSTer had too be updated too, probably because of this:
> Report image size 0 if no save available

**Comment by RetroDriven** [comment] 2019-03-05 05:38
I'm running the latest Mister main and SNES Core but I'm still having the same issue. Maybe it's my Rom?

**Comment by James-F2** [comment] 2019-03-05 05:40
Sorry forgot to mention that it is with March 4th commits that I compiled, they will be included with the next release.

**Comment by James-F2** [comment] 2019-03-09 07:14
Works perfectly with latest release.

**Closed** 2019-03-24 02:52 UTC
